res: 100 
order: 3
timescale: 3
increment: 0.25 
control_pts: 
  - [0,0,0] 
  - [0,0,0]
  - [0,0,0]
  - [3,0,0]
  - [16,7,0]
  - [12,14,0]
  - [7,1,0]
  - [0,20,0]
  - [-10,17,0]
  - [-3,8,0]
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]